name: real_estate_app
description: "This is a flutter engineer test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  svg_flutter: ^0.0.1
  animated_flip_counter: ^0.3.4
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/euclid/
    - assets/images/

  fonts:
    - family: Euclid
      fonts:
        - asset: assets/fonts/euclid/Euclid-Circular-A-Bold.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Bold-Italic.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Italic.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Light.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Light-Italic.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Medium.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Medium-Italic.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Semibold.ttf
        - asset: assets/fonts/euclid/Euclid-Circular-A-Semibold-Italic.ttf