name: real_estate_app
description: "This is a flutter engineer test"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  google_maps_flutter: ^2.7.0
  svg_flutter: ^0.0.1
  animated_flip_counter: ^0.3.4
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Sofia
      fonts:
        - asset: assets/fonts/sofia/SofiaSans-Black.ttf
        - asset: assets/fonts/sofia/SofiaSans-BlackItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-Bold.ttf
        - asset: assets/fonts/sofia/SofiaSans-BoldItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-ExtraBold.ttf
        - asset: assets/fonts/sofia/SofiaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-ExtraLight.ttf
        - asset: assets/fonts/sofia/SofiaSans-ExtraLightItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-Italic.ttf
        - asset: assets/fonts/sofia/SofiaSans-Light.ttf
        - asset: assets/fonts/sofia/SofiaSans-LightItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-Medium.ttf
        - asset: assets/fonts/sofia/SofiaSans-MediumItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-Regular.ttf
        - asset: assets/fonts/sofia/SofiaSans-Semibold.ttf
        - asset: assets/fonts/sofia/SofiaSans-SemiboldItalic.ttf
        - asset: assets/fonts/sofia/SofiaSans-Thin.ttf
        - asset: assets/fonts/sofia/SofiaSans-ThinItalic.ttf